# Generated by Django 5.0.7 on 2024-11-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen_type', models.CharField(choices=[('Food - Wheat', 'Food - Wheat'), ('Food - Nuts', 'Food - Nuts'), ('Food - Dairy', 'Food - Dairy'), ('Food - Seafood', 'Food - Seafood'), ('Environmental - Pollen', 'Environmental - Pollen'), ('Environmental - Dust', 'Environmental - Dust'), ('Environmental - Mold', 'Environmental - Mold'), ('Environmental - Insect', 'Environmental - Insect'), ('Food - Spices', 'Food - Spices')], max_length=50)),
                ('ige_levels', models.FloatField()),
                ('exposure_frequency', models.CharField(choices=[('Rarely', 'Rarely'), ('Monthly', 'Monthly'), ('Daily', 'Daily'), ('Seasonal', 'Seasonal')], max_length=20)),
                ('symptoms', models.CharField(max_length=50)),
                ('family_history', models.CharField(max_length=3)),
                ('reaction_severity', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
