# Generated by Django 5.0.7 on 2024-11-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_allergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectrolyteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serum_sodium', models.FloatField()),
                ('serum_potassium', models.FloatField()),
                ('serum_calcium', models.FloatField()),
                ('serum_magnesium', models.FloatField()),
                ('bicarbonate', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('outcome', models.CharField(max_length=50)),
            ],
        ),
    ]
